APP: "mars"
MODE: "release"

# 容器部署
CONTAINER: false

# 组织名称 服务树初始节点
ORGANIZATION: "icsoc" 
# 树节点组织展示的名称
LABEL: "中通天鸿" #组织中文名


# 用于自动生成命名空间下secret 拉取docker认证配置 编译机上执行: cat ~/.docker/config.json | base64 -w 0
SECRECT: "ewoJImF1dGhzIjogewoJCSIxNzIuMjUuMi4xNzQiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2U0dGeVltOXlNVEl6TkRVPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDkuOSAobGludXgpIgoJfQp9"

# 日志配置
LOG:
  LOGFILE: "/tmp/log/mars/app.log"
  ACCESSLOGFILE: "/tmp/log/mars/access.log"

#应用http监听接口
HTTP:
  LISTEN: ":9001"

# jupiter用户权限认证rpc
JUPITER: 
  - "127.0.0.1:9012"

MYSQL:
  addr: "root:Passw0rd@tcp(127.0.0.1:3306)/mars?charset=utf8&parseTime=true&loc=Local"
  maxConns: 1000
  maxIdle: 100

# CI配置
CI:
  # 编译路径
  cp: "/tmp/ci"


