APP: "mars"
# release
MODE: "release"

# 组织名称 服务树初始节点
ORGANIZATION: "icsoc" 
# 树节点组织展示根节点名称
LABEL: "中通天鸿" 


# 用于自动生成命名空间下secret 拉取docker认证配置 编译机上执行: cat ~/.docker/config.json | base64 -w 0
SECRECT: "ewoJImF1dGhzIjogewoJCSIxNzIuMjUuMi4xNzQiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2U0dGeVltOXlNVEl6TkRVPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDkuOSAobGludXgpIgoJfQp9"

# 日志配置
LOG:
  LOGFILE: "/data/log/mars/app.log"
  ACCESSLOGFILE: "/data/log/mars/access.log"

#应用http监听接口
HTTP:
  LISTEN: ":9001"

RPC:
  LISTEN: ":9013"

# jupiter用户权限认证rpc
JUPITER: 
  - "127.0.0.1:9012"

MYSQL:
  addr: "root:Passw0rd@/mars?charset=utf8&parseTime=true&loc=Local"
  maxConns: 1000
  maxIdle: 100



  