app: "saturn"
mode: "release"
DEBUG: false
CONTAINER: true
#系统启动会生成默认策略
defaultStrategyId: 1 
# 钉钉、企业微信、飞书告警消息中带出的静默地址,监控平台saturn的地址
SilenceDomain: "http://gops-demo.icsoc.net"
log: 
  logfile: "/data/log/saturn.log"
  accesslogfile: "/data/log/saturn-access.log"

http: 
  enabled: true
  listen: ":9003"

# 用户管理平台,rpc调用获取用户信息用于告警
JUPITER: 
  - "gops-jupiter:9012"

# 产品线管理平台，rpc调用获取告警产品线信息
MARS:
  - "gops-mars:9013"

mysql: 
  addr: "hiops:Passw0rd@tcp(gops-db:3306)/saturn?charset=utf8&parseTime=true&loc=Local"
  maxConns: 1000
  maxIdle: 100





