APP: "jupiter"
MODE: "release"
CONTAINER: true
LOG: 
  LOGFILE: "/data/log/jupiter/app.log"
  ACCESSLOGFILE: "/data/log/jupiter/access.log"

HTTP: 
  LISTEN: ":9002"

RPC:
  LISTEN: ":9012"

MYSQL: 
  addr: "hiops:Passw0rd@tcp(gops-db:3306)/jupiter?charset=utf8&parseTime=true&loc=Local"
  maxConns: 1000
  maxIdle: 100

