app: "jupiter"
mode: "release"
# 容器部署
CONTAINER: false
LOG: 
  LOGFILE: "/data/log/gops/jupiter/app.log"
  ACCESSLOGFILE: "/data/log/gops/jupiter/access.log"

HTTP: 
  LISTEN: ":9002"

RPC:
  LISTEN: ":9012"

MYSQL: 
  addr: "root:Passw0rd@/jupiter?charset=utf8&parseTime=true&loc=Local"
  maxConns: 1000
  maxIdle: 100

