APP: "jupiter"
MODE: "debug"
LOG: 
  LOGFILE: "/data/log/jupiter/app.log"
  ACCESSLOGFILE: "/data/log/jupiter/access.log"

HTTP: 
  LISTEN: ":9002"

RPC:
  LISTEN: ":9012"

MYSQL: 
  addr: "root:Passw0rd@/jupiter?charset=utf8&parseTime=true&loc=Local"
  maxConns: 1000
  maxIdle: 100

